const Questions = [
    {
        question: "What is your main fitness goal?",
        id: 0,
        answerA: "Gain more flexibility and mobility",
        idNextQuestionA: 4,
        answerB: "Improve my posture and fix my movement patterns during daily activities and/or in the gym",
        idNextQuestionB: 5,
        answerC: "Tone/gain muscle, improve my cardiovascular health, lose weight, and improve overall fitness",
        idNextQuestionC: 1,
        answerD: "Prepare for a race and/or improve cardiovascular health",
        idNextQuestionD: 6,
        answerE: "Work 1-on-1 remotely with a trainer to improve overall fitness including flexibility/mobility, strength, cardivoascular health, and agility",
        programResultE: "Online Tailored Personal Training",
        programLinkE: "/Online",
    },
    {
        question: "What weights are available to you?",
        id: 2,
        answerA: "I have no fitness equipment (body weight)",
        programResultA: "Body Weight Fitness Training Program",
        programLinkA: "/FullBody",
        answerB: "I have bands and dumbbells available",
        programResultB: "Full Body Fitness Bands & Dumbbells",
        programLinkB: "/FullBody",
        answerC: "I have bands and dumbbells but would like to do a body weight routine",
        programResultC:"Body Weight Fitness Training Program",
        programLinkC: "/FullBody",
        answerD: "I have a full gym available",
        programResultD: "Full Body Fitness Gym Access",
        programLinkD: "/FullBody",
        answerE: "I have full gym access but would like to do a body weight routine",
        programResultE: "Body Weight Fitness Training Program",
        programLinkE: "/FullBody",
    },
    {
        question: "How much time do you have to exercise per session?",
        id: 1,
        answerA: "30 minutes or less",
        idNextQuestionA: 8,
        answerB: "30-60 minutes",
        idNextQuestionB: 8,
        answerC: "60 minutes or more",
        idNextQuestionC: 2,
        answerD: "My schedule is not consistent, most weeks I have less than 60 minutes",
        idNextQuestionD: 8,
        answerE: "My schedule is not consistent, most weeks I have more than 60 minutes",
        idNextQuestionE: 2,
    },
    {
        question: "What level of programming are you looking for from our services?",
        id: 4,
        answerA: "I would like an in-depth pre-written progressive program that includes assistive videos and PDFs",
        programResultA:  "Mobility & Flexibility 8 week",
        programLinkA: "/MobilityEightWeek",
        answerB: "I would like access to independent videos to help me build/check my own workouts",
        programResultB: "Mobility & Flexibility Videos",
        progarmLinkB: "/MobilityHowTo",
        answerC: "I would just like access to PDFs to help me build/check my own workouts",
        programResultC: "Mobility & Flexibility PDF",
        programLinkC: "/MobilityPDF",
        answerD: "I would like a program created specifically for me month to month by a trainer that includes daily communication and nutrition suggestions ",
        programResultD: "Online Tailored Personal Training",
        programLinkD: "/Online",
        answerE: "I am not sure",
        programResultE: "Online Tailored Personal Training",
        programLinkE: "/Online",
    },
    {
        question: "What level of programming are you looking for from our services?",
        id: 5,
        answerA: "I would like an in-depth pre-written progressive program that includes assistive videos and PDFs",
        programResultA: "Posture & Correctives 8 week",
        programLinkA: "/PostureFormEightWeek",
        answerB: "I would like access to independent videos to help me build/check my own workouts",
        programResultB: "Posture & Correctives Videos",
        programLinkB: "/PostureFormHowTo",
        answerC: "I would just like access to PDFs to help me build/check my own workouts",
        programResultC: "Posture & Correctives PDF",
        programLinkC: "/PostureFormPDF",
        answerD: "I would like a program created specifically for me month to month by a trainer that includes daily communication and nutrition suggestions ",
        programResultD: "Online Tailored Personal Training",
        programLinkD: "/Online",
        answerE: "I am not sure",
        programResultE: "Online Tailored Personal Training",
        programLinkE: "/Online",
    },
    {
        question: "What level of programming are you looking for from our services?",
        id: 8,
        answerA: "I would like an in-depth pre-written progressive program that includes assistive videos",
        programResultA: "HIIT 8-week Fitness Training",
        programLinkA: "/HIITprograms",
        answerB: "I would like access to independent videos to help me build/check my own workouts",
        programResultB: "HIIT Videos",
        programLinkB: "/HIITvideos",
        answerC: "I would like a program created specifically for me month to month by a trainer that includes daily communication and nutrition suggestions ",
        programResultC: "Online Tailored Personal Training",
        programLinkC: "/Online",
        answerD: "I am not sure",
        programResultD: "Online Tailored Personal Training",
        programLinkD: "/Online",
        answerE:  "I would just like access to exercise PDFs to help me build/check my own workouts",
        programResultE: "HIIT PDF",
        programLinkE: "",
    },
    {
        question: "what length of race are you wanting to train for?",
        id: 6,
        answerA: "5k",
        programResultA: "5k Training Program",
        programLinkA: "/5k",
        answerB: "Half-Marathon",
        programResultB: "Half-Marathon Training Program",
        programLinkB: "/Half",
        answerC: "Marathon",
        programResultC: "Marathon Training Program",
        programLinkC: "Marathon",
        answerD: "I am not sure, I am new to running and would like to improve my cardiovascular health",
        programResultD: "5k Training Program",
        programLinkD: "/5k",
        answerE: "I am not sure, I currently run (can run 3+ miles consistenly) and would like to improve my running abilities",
        programResultE: "5k Training Program or Half-Marathon Training Program",
        programLinkE: "/Running",
    }
];

export default Questions;